const TODO = "TODO";
const ADD_TODO = "ADD_TODO";
const EDIT_TODO = "EDIT_TODO";
const REMOVE_TODO = "REMOVE_TODO";
const CHANGE_TODO_STATUS = "CHANGE_TODO_STATUS";
const ARCHIVE_TODO = "ARCHIVE_TODO";
export {
  TODO,
  ADD_TODO,
  CHANGE_TODO_STATUS,
  EDIT_TODO,
  REMOVE_TODO,
  ARCHIVE_TODO,
};
